name: Coverage

on:
  pull_request:
    branch:
      - '*'
jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: rm -rf package-lock.json cache artifacts typechain-types coverage.json gas-report.txt && npm install

    - name: Coverage
      run: npx hardhat coverage

    # - name: Debug Coverage
    #   run: |
    #     ls -l coverage
    #     cat coverage.json

    # - name: Comment Test Coverage
    #   uses: AthleticNet/comment-test-coverage@1.1
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     path: ./coverage/index.html
    #     title: Karma Test Coverage

    - name: Comment Coverage Screenshot
      uses: saadmk11/comment-webpage-screenshot@main
      with:
        # Optional, the action will create a new branch and
        # upload the screenshots to that branch.
        upload_to: github_branch  # Or, imgur
        # Optional, the action will capture screenshots
        # of all the changed html files on the pull request.
        capture_changed_html_files: yes  # Or, no
        # Optional, the action will capture screenshots
        # of the html files provided in this input.
        # Comma seperated file paths are accepted
        capture_html_file_paths: "./coverage/index.html"
        # Optional, the action will capture screenshots
        # of the URLs provided in this input.
        # You can add URLs of your development server or
        # run the server in the previous step
        # and add that URL here (For Example: http://172.17.0.1:8000/).
        # Comma seperated URLs are accepted.
        github_token: ${{ secrets.GITHUB_TOKEN }}


