name: Coverage

on:
  pull_request:
    branch:
      - '*'
jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: rm -rf package-lock.json cache artifacts typechain-types coverage.json gas-report.txt && npm install

    - name: Coverage
      run: npx hardhat coverage

    - name: Find the PR
      uses: jwalton/gh-find-current-pr@v1
      id: findPr

    - name: Comment with Test Coverage
      uses: Nef10/lcov-reporter-action@v0.3.0
      with:
        lcov-file: ./coverage/lcov.info
        pr_number: ${{ steps.findPr.outputs.number }}
        github-token: ${{ secrets.GITHUB_TOKEN }}


